# Generated by Django 4.1.7 on 2023-02-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_user_icon_alter_user_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, height_field=200, upload_to='uploads/users/', width_field=200),
        ),
    ]
