# Generated by Django 4.1.7 on 2023-02-24 05:31

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, height_field='200', upload_to=organizations.models.User.path_and_rename, width_field='200'),
        ),
    ]
