# Generated by Django 4.1.7 on 2023-02-24 11:36

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.User.path_and_rename),
        ),
    ]
